width: 32
height: 32
channels: 3
num_classes: 10
files_location: /scratch/pl2285/ddpm/torchvision_dataset
train:
  _target_: torchvision.datasets.CIFAR10
  root: ${dataset.files_location}
  train: true
  download: true
  transform:
    _target_: torchvision.transforms.ToTensor
val:
  _target_: torchvision.datasets.CIFAR10
  root: ${dataset.files_location}
  train: false
  download: true
  transform:
    _target_: torchvision.transforms.ToTensor
